FROM {{ env.base_image }}

WORKDIR /app

{{ env.docker_file_commands }}

COPY ./requirements.txt /app/requirements.txt

RUN python -m pip install --no-cache-dir -r /app/requirements.txt

COPY ./main.py /app/

CMD ["uvicorn",\
    "main:app", \
    "--port", "{{ env.port }}",\
    "--host", "0.0.0.0"]
