FROM python:3.11-slim

WORKDIR /app

COPY .requirements.txt /app/requirements.txt

RUN python -m pip install --no-cache-dir -r /app/requirements.txt

COPY ./main.py /app/

CMD ["uvicorn",\
    "main:app", \
    "--port", "{{ env.port }}",\
    "--host", "{{ env.host }}"]
